name: Create release pull request

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".changeset/**.md"

jobs:
  validate:
    name: Validate and create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run packages:rollup

      - name: Test packages
        run: pnpm run packages:test

      - name: Lint packages
        run: pnpm run packages:lint

      - name: Create version pull request
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          commit: 'chore(packages): version packages'
          title: 'chore(packages): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}