name: deploy-docs
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version:
          dest:
          run_install:
      - run: pnpm i
      - run: pnpm run docs:deploy