name: Release @twa.js packages

run-name: Release @twa.js packages

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "packages/bridge/src/**"
      - "packages/init-data/src/**"
      - "packages/sdk/src/**"
      - "packages/sdk-react/src/**"
      - "packages/utils/src/**"

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Run linter
        run: pnpm run ci:lint

      - name: Build packages
        run: pnpm run ci:packages:build

      - name: Run tests
        run: pnpm run ci:test

      - name: "Configure Git"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://${{github.actor}}:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run ci:packages:publish