name: Release @twa.js packages

run-name: Release @twa.js packages

on: workflow_dispatch

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    steps:
      # Setup node.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install pnpm
      - name: Install pnpm
        run: npm i -g pnpm

      # Install dependencies.
      - name: Install dependencies
        run: pnpm i

      - name: Test packages
        run: pnpm run test

      - name: Apply linter
        run: pnpm run lint

      - name: Build packages
        run: pnpm run build

      - name: Publish packages
        run: pnpm run publish --no-private -y