name: Release @twa.js packages

run-name: Release @twa.js packages

on: workflow_dispatch

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    steps:
      # Setup node.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      # Install dependencies.
      - name: Install dependencies
        run: pnpm i

      # Run linter.
      - name: Run linter
        run: pnpm run ci:lint

      # Build packages.
      - name: Build packages
        run: pnpm run ci:build:packages

      # Run tests.
      - name: Run tests
        run: pnpm run ci:test

      # Publish packages.
      - name: Publish packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config --global set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          pnpm config ls -l
          pnpm run ci:publish --loglevel silly