name: Test @twa.js packages

run-name: Test @twa.js packages

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "packages/**"
      - "!packages/documentation/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Setup node.
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      # Install dependencies.
      - name: Install dependencies
        run: pnpm i

      # Run linter.
      - name: Run linter
        run: pnpm run ci:lint

      # Build packages.
      - name: Build packages
        run: pnpm run ci:packages:build

      # Run tests.
      - name: Run tests
        run: pnpm run ci:test