name: Test @twa.js packages

run-name: Test @twa.js packages

on:
  pull_request:
    branches:
      - master
    paths:
      - packages/*
      - !packages/documentation

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      # Setup node.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install pnpm
      - name: Install pnpm
        run: npm i -g pnpm

      # Install dependencies.
      - name: Install dependencies
        run: pnpm i

      # Run tests and linter.
      - name: Run tests
        run: pnpm run test && pnpm run lint