name: Test Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - "master"

jobs:
  validate:
    name: Validate packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm run packages:rollup

      - name: Test packages
        run: pnpm run packages:test

      - name: Lint packages
        run: pnpm run packages:lint